version: "3"

services:
  note_service:
    build:
      context: ./
      dockerfile: ./Dockerfile/DockerfileNote
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - rabbitmq
  producer_service:
    build:
      context: ./
      dockerfile: ./Dockerfile/DockerfileProducer
    restart: always
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: postgres
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_DB: "note_service"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../init/postgres:/docker-entrypoint-initdb.d
    ports:
      - "65432:5432"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  rabbitmq:
    image: rabbitmq:3.10.5-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "user"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres:
  redis:
