Services:
  Note:
    MaxTitleLength: 100
    MaxContentLength: 1000
    Repository:
      CreateNotesBatchSize: 5
Adapters:
  Auth:
    Address: "localhost:5000"
    BackupStorageTime: 60
  Server:
    Addr: :3001
    ReadTimeout: 5
  RabbitMQ:
    Host: rabbitmq
    Port: 5672
    UserName: user
    Password: user
    QueueName: note_service
  Postgres:
    Host: postgres
    Port: 5432
    UserName: postgres
    Password: 1234
    DBName: note_service
    SSLMode: disable
    PoolSize: 100
  Redis:
    Host: redis
    Port: 6379
    DB: 0
Common:
  Logger:
    Level: info
  CircuitBreaker:
    RecordLength: 100
    Timeout: 5000
    Percentile: 0.3
    RecoveryRequests: 10
